### ISSUE TITLE
Cannot delete subfolder

### ISSUE THREAD

**Issue by anjos** [RhetTbull/PhotoScript#35]
I'm reaching an exception deleting a subfolder:

```python
import photoscript

library = photoscript.PhotosLibrary()
A = library.create_folder("A")
B = library.create_folder("B", folder=A)
library.delete_folder(B)
```

will crash on macOS 13.0 (22A380) with the following exception like so:

```
Traceback (most recent call last):
  File "/Users/andre/work/anjos/photos/./move-albums-up.py", line 93, in <module>
    if __name__ == "__main__":
  File "/Users/andre/mamba/envs/photos/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andre/mamba/envs/photos/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/andre/mamba/envs/photos/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andre/mamba/envs/photos/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/andre/work/anjos/photos/./move-albums-up.py", line 86, in move_albums_up
    __import__("ipdb").set_trace()
  File "/Users/andre/mamba/envs/photos/lib/python3.10/site-packages/photoscript/__init__.py", line 459, in delete_folder
    return run_script("_photoslibrary_delete_folder", folder.id)
  File "/Users/andre/mamba/envs/photos/lib/python3.10/site-packages/photoscript/script_loader.py", line 18, in run_script
    return SCRIPT_OBJ.call(name, *args)
  File "/Users/andre/mamba/envs/photos/lib/python3.10/site-packages/applescript/__init__.py", line 110, in call
    return self._unpackresult(*self._script.executeAppleEvent_error_(evt, None))
  File "/Users/andre/mamba/envs/photos/lib/python3.10/site-packages/applescript/__init__.py", line 65, in _unpackresult
    raise ScriptError(errorinfo)
applescript.ScriptError: Photos got an error: Can’t get folder id "5AF03046-5BC8-4962-AB48-7E734934B264/L0/020" of folder id "75335F9A-8084-4D5F-9ED7-AC645A663CB0/L0/020" of folder id "7F82BB6F-9596-4E73-B4C5-6A3FDD9E1758/L0/020". (-1728) app='Photos' range=14097-14116
```

Any ideas on how to circumvent this issue?

**Comment by anjos** [comment]
For information, `library.delete_folder(A)` removes the whole hierarchy as expected.

**Comment by RhetTbull** [comment]
I’ll take a look. I think I know what’s going on.  The Photos AppleScript interface doesn’t provide direct access to sub folders — the code will have to traverse the folder tree and tell the parent folder to delete the sub folder. May be a little while before I can get to this as I’ve got several other projects on the front burners.

**Comment by RhetTbull** [comment]
Looks like I tried to tackle this once before:

https://github.com/RhetTbull/PhotoScript/blob/3d64c526c8edbccc16f4d7da64214c019d7b4bc8/photoscript/photoscript.applescript#L516-L532

**Comment by RhetTbull** [comment]
As I've dug into this, I think it may not be possible to fix. This appears to be due to a bug in the Photos AppleScript interface introduced in Catalina and still remaining.  Apple doesn't seem interested in fixing it (though I will file a bug report with them).  Sub folders can be deleted on Mojave and below but apparently not on Catalina+

One possible workaround (that's a bit hacky) could be to recreate the folder and album structure while pruning the subfolder you want to delete. This would not be efficient but is likely possible to implement. I already do something similar for removing photos from albums (this is something not allowed by Photos but PhotoScript emulates this by creating a new album with the same name then deleting the original album).

**Comment by anjos** [comment]
Right.  In my use-case, this issue does not annoy me that much.  If too painful to fix, may be consider closing this as "won't fix".
